name: Deploy to tilde.town

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: tilde.town
          username: azee
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/public_html
            git pull origin main
